---
title: "Circadian Expression Detection"
author: "Ziang Zhang"
date: "2024-06-14"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r}
library(BayesGP)
library(TMB)
library(Matrix)
library(splines)
library(parallel)
library(ggplot2)
library(reshape2)
library(mixsqp)
library(tidyverse)
cpp_dir <- paste0(getwd(), "/code/cpp")
fig_dir <- paste0(getwd(), "/output/circadian_expression")
result_dir <- paste0(getwd(), "/output/circadian_expression")
function_dir <- paste0(getwd(), "/code/function")
data_dir <- paste0(getwd(), "/data/circadian_expression")
source(paste0(function_dir, "/functions_fitting_Poisson_circadian_expression.R"))
compile(paste0(cpp_dir, "/Poisson_expression.cpp"))
compile(paste0(cpp_dir, "/Poisson_just_fixed_expression.cpp"))
dyn.load(TMB::dynlib(paste0(cpp_dir, "/Poisson_expression")))
dyn.load(TMB::dynlib(paste0(cpp_dir, "/Poisson_just_fixed_expression")))
num_cores <- 4
```



```{r}
# Load data
load(file = paste0(data_dir, "/circ_data.rda"))
```

## Focus on Group C first:

```{r}
datasets <- list()
all_gene <- unique(gene_exp_data_c$gene_id)
for (gene in all_gene) {
  selected_row <- gene_exp_data_c %>% filter(gene_id == gene)
  datasets[[gene]] <- data.frame(x = seq(0, 44, by = 4))/24
  datasets[[gene]]$y <- as.numeric(selected_row[-c(1,2)])
}
save(datasets, file = paste0(result_dir, "/datasets.rda"))
```

```{r}
datasets <- list()
all_gene <- unique(gene_exp_data_c$gene_id)
load(paste0(result_dir, "/datasets.rda"))
```

To ensure the accuracy of the marginal likelihood approximation, we should filter out the genes with extremely small number of counts

```{r}
datasets_original <- datasets
datasets <- list()
for (gene in all_gene) {
  if(min(datasets_original[[gene]]$y) > 100) {
    datasets[[gene]] <- datasets_original[[gene]]
    datasets[[gene]]$y <- round(datasets[[gene]]$y)
  }
}
# update all_gene
all_gene <- datasets %>% names()
```



Compute the library size:

```{r}
size_vec <- numeric(length = nrow(datasets[[1]]))
for (i in 1:length(size_vec)) {
  all_counts <- unlist(lapply(datasets, function(x) {x$y[i]}))
  size_vec[i] <- sum(all_counts)
}
log_size_vec <- log(size_vec)
```


Visualize 16 of the datasets:

```{r}
par(mfrow = c(4, 4))
for (i in 1:16) {
  gene <- all_gene[i]
  plot(datasets[[gene]]$x, datasets[[gene]]$y, type = "o", 
       col = "blue", lwd = 2, xlab = "Time", ylab = "Expression")
  abline(v = 1, lty = 2)
}
par(mfrow = c(1, 1))
```

Make up an example for sanity check:

```{r}
datasets[[11371]] <- data_frame(x = seq(0, 44, length.out = 12)/24)
linear_pred <- log_size_vec - 14 + sin(datasets[[11371]]$x*2*pi)*datasets[[11371]]$x*2
datasets[[11371]]$y <- rpois(12, exp(linear_pred))
plot(datasets[[11371]]$x, datasets[[11371]]$y, type = "o", log = "y",
     col = "blue", lwd = 2, xlab = "Time", ylab = "Expression")
# add abline for each period
abline(v = seq(0, 2, by = period), lty = 2)
```


```{r}
m <- 1 # 1 harmonics
k <- 25
indx <- 11371
psd_sgp_vector <- seq(0, 3, by = 0.1)

## Estimate the dominant frequency of datasets[[indx]]$y
time_series <- ts(datasets[[indx]]$y, frequency = 6)
# do not show the plot
dd <- spectrum(time_series, method = c("pgram"), plot = F)
period <- (1/dd$freq)[which.max(dd$spec)]
if(period > 1 || period < 0.8){
  period <- 1
}
betaprec <- 1e-10

plot(datasets[[indx]]$x, datasets[[indx]]$y, type = "o", log = "y",
     col = "blue", lwd = 2, xlab = "Time", ylab = "Expression")
# add abline for each period
abline(v = seq(0, 2, by = period), lty = 2)

# # Detrending the expression
# glm_fit <- glm(datasets[[indx]]$y ~ datasets[[indx]]$x, family = poisson(), offset = log_size_vec)
# update_offset <- as.vector(cbind(1, datasets[[indx]]$x) %*% coef(glm_fit))
update_offset <- 0

# ## Just centering the expression
# glm_fit <- glm(datasets[[indx]]$y ~ 1, family = poisson(), offset = log_size_vec)
# update_offset <- as.vector(cbind(1) %*% coef(glm_fit))


like_vec <- compute_log_likelihood_sBspline_seq(dataset = datasets[[indx]], 
                                    period = period, num_knots = k, 
                                    psd_sgp_vector = psd_sgp_vector, pred_step = period,
                                    betaprec = betaprec, 
                                    log_lib_size = (log_size_vec + update_offset),
                                    m = m)
p <- 4
k <- 50
like_vec2 <- compute_log_likelihood_ospline_seq(dataset = datasets[[indx]], 
                                    num_knots = k, 
                                    p = p,
                                    psd_iwp_vector = psd_sgp_vector, 
                                    pred_step = period,
                                    betaprec = betaprec, 
                                    log_lib_size = (log_size_vec + update_offset)
                                    )

plot(psd_sgp_vector, like_vec, type = "l", col = "blue", lwd = 2, xlab = "psd", ylab = "log likelihood", ylim = range(c(like_vec, like_vec2)))
lines(psd_sgp_vector, like_vec2, col = "red", lwd = 2)
legend("bottomright", legend = c("sGP", "IWP"), col = c("blue", "red"), lty = 1:1, cex = 0.8)

```








